### ISSUE TITLE
How to train our own dataset?

### ISSUE THREAD

**Issue by rockywind** [gerwang/ShadowNeuS#1]
Hi, thank you for your sharing the great work!
My dataset is the same as [kitti dataset](https://www.cvlibs.net/datasets/kitti/).
Can you sharing me the code for transforming the own data to the ShadowNeuS training dataset?

**Comment by gerwang** [comment]
Hi @rockywind, thanks for your interest in our work!

To get to know the data format, [the script to generate our blender data](https://drive.google.com/drive/u/1/folders/1-UYHsB7byzjcUTXj6_SvLjO2PuE6nngA) is a good starting point. You can also generate your own data by modifying the .blend files in Blender.

Our method requires capturing the object in different light directions. On an outdoor dataset like KITTI, this can be done by capturing at multiple times of the day. Calculating the sun from the geographic location and the time of day is a possible way to get the light direction. Handling street-level scenes is interesting but left as future work. If you have questions when trying, please let me know.
