### ISSUE TITLE
About how to prepare the custom data

### ISSUE THREAD

**Issue by liulisixin** [gerwang/ShadowNeuS#2]
Dear Gerwang,

Thank you for your kind sharing! Your project is amazing!

Could you please explain something about how to prepare the training data? For example, .json, floor, normal in synthetic data, and .npz in real data. In other word, how could we apply your project on the custom data?

Thank you a lot in advance!

Regards,
Yixiong

**Comment by gerwang** [comment]
Hi @liulisixin, thanks for your interest!

To prepare the synthetic data, you can see the scripts to generate the blender data at [here](https://drive.google.com/drive/u/1/folders/1-UYHsB7byzjcUTXj6_SvLjO2PuE6nngA). To prepare the real data, I just uploaded the script and raw data at [process_real_dataset.ipynb](https://github.com/gerwang/ShadowNeuS/blob/main/preprocess_custom_data/colmap_preprocess/process_real_dataset.ipynb), you can follow this notebook to see how we processed the real dataset.

**Comment by liulisixin** [comment]
Hi @gerwang ,

Thank you for your kind and rapid reply!

Your updating is really helpful. I will follow the notebook to run my experiment. 

Thanks a lot.

**Comment by liulisixin** [comment]
Dear Gerwang,

Could I ask you one more question? 

What is the coordinate system (the direction of xyz) you used in your work? Did you use the same coordinate system as NeuS? 

Thank you a lot in advance!

Best regards,
Yixiong

**Comment by gerwang** [comment]
We use the same coordinate system as NeuS. The object locates in a bounding sphere centered at the origin, with radius `bound_r` (see the configuration files).

**Comment by liulisixin** [comment]
Thank you for your reply!

As I understand, it is: from the point of view of the camera, the three axes XYZ are [right, down, forwards]. Am I right?

Sorry for my annoying. I just want to make sure about it.

**Comment by gerwang** [comment]
Not exactly. Using top-down data, three axes XYZ roughly match left, down, and backward. We use world coordinates, the same as NeuS, instead of camera coordinates.

**Comment by liulisixin** [comment]
> Not exactly. Using top-down data, three axes XYZ roughly match left, down, and backward. We use world coordinates, the same as NeuS, instead of camera coordinates.

Ok, thank you for your patient reply. You are so kind!
